name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker://srzzumix/googletest:latest

    steps:
      - uses: actions/checkout@v2

      - name: Create main
        run:  g++ main.cpp -o main -lgtest -lpthread

      - name: Run programm
        run: ./main
      - name: Send files
        uses: actions/upload-artifact@v2.3.1
        with:
            name: build
            path: main

